import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Button } from '../components/ui/button.js'; // Adjust path as per your file structure
import WeaveXLogo from '../pages/logo.js'; // Adjust path as per your file structure
import { FaDiscord } from "react-icons/fa6";
import { BsTwitterX } from "react-icons/bs";
export const Center = () => {
    return (_jsx("div", { className: "bg-gray-900 min-h-screen text-white flex flex-col justify-center items-center p-8", children: _jsxs("div", { className: "text-center max-w-3xl mb-12", children: [_jsxs("div", { className: "flex flex-col items-center mb-8", children: [_jsx(WeaveXLogo, {}), _jsx("h1", { className: "text-6xl font-bold font-serif mb-2", children: "Welcome to" }), _jsx("h1", { className: "text-6xl font-bold font-serif text-purple-400 mb-4", children: "WeaveX" })] }), _jsx("p", { className: "text-2xl text-slate-400 mb-4", children: "WeaveX aggregates the latest and most innovative resources, tools, and insights from the Web3 and decentralized technology ecosystem." }), _jsx("p", { className: "text-lg text-slate-500 mb-8", children: "Whether you're a developer looking for the latest DeFi protocols, a blockchain enthusiast searching for news, or a business seeking to integrate decentralized solutions, WeaveX has you covered." }), _jsxs("div", { className: "flex flex-col items-center", children: [_jsx(Button, { className: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-4 px-6 rounded-full mt-4", children: "Explore Now" }), _jsx("p", { className: "text-lg text-slate-400 mt-4", children: "Join our community and stay ahead in the world of Web3." })] }), _jsxs("div", { className: "flex justify-center items-center ", children: [_jsx("a", { href: "https://discord.com", target: "_blank", rel: "noreferrer", className: " text-slate-500 font-semibold py-2 px-4 border border-transparent", children: _jsx(FaDiscord, { className: "ml-0 position absolute bottom-10 size-10" }) }), _jsx("a", { href: "https://twitter.com", target: "_blank", rel: "noreferrer", className: " text-slate-500 font-semibold py-2 px-4 border border-transparent", children: _jsx(BsTwitterX, { className: "ml-4 position absolute bottom-11 size-8" }) })] })] }) }));
};
export default Center;
